---
# This play adds the filter rules to a content view filter
# Hopefully the satellite collection is updated at some point and this
# process becomes more manageable

# We call this once for each filter rule
# We determine based on the parameters the rule type
# We call the proper version of the module depending on the content type 
# Content types are:
# 'rpm', 'package_group', 'erratum', 'docker', 'modulemd'
# The upstream is splitting out Filters and Filter rules... go figure.
# This means that this is currently dead code and will not work.
# Print a debug message indicating manual intervention is required
# Return success
