---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Get a test value
  set_fact:
    test_value: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- name: Write test value to disk
  copy:
    dest: /root/testvalue.txt
    content: "{{ test_value }}"
    force: yes
  
- name: Debug
  debug:
    var: hostvars
    
- name: Copy the code
  ansible.builtin.template: 
    src: "{{ item }}.j2"
    dest: "/var/www/html/{{ item }}"
  loop:
    - index.html
    - about.html
    - index.php
